FROM testsshd

RUN apt install -y build-essential make golang libpam-dev pamtester vim ca-certificates git
RUN echo 'auth required pam_authy.so' >> /etc/pam.d/sshd
RUN sed -i 's/^ChallengeResponseAuthentication no$/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
COPY data.conf /etc/pam_authy.conf
RUN chown root:root /etc/pam_authy.conf
RUN chmod 600 /etc/pam_authy.conf
